"""Generate frontend/data.js from backend data modules.

Run this at build/deploy time to create a static JS file so the frontend
does not need to fetch categories and states from the API on page load.

Usage:
    python scripts/generate_frontend_data.py
"""
import json
import os
import sys

# Allow imports from project root
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from backend.data.categories import category_options
from backend.data.states import US_STATE_CITIES


def main():
    output_path = os.path.join(
        os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
        "frontend", "data.js",
    )

    states_list = sorted(US_STATE_CITIES.keys())

    with open(output_path, "w", encoding="utf-8") as f:
        f.write("// Auto-generated by scripts/generate_frontend_data.py — do not edit.\n")
        f.write("const CATEGORIES=")
        json.dump(category_options, f, ensure_ascii=False, separators=(",", ":"))
        f.write(";\nconst US_STATES=")
        json.dump(states_list, f, ensure_ascii=False, separators=(",", ":"))
        f.write(";\n")

    size_kb = os.path.getsize(output_path) / 1024
    print(f"Generated {output_path} ({size_kb:.1f} KB)")


if __name__ == "__main__":
    main()
