#!/usr/bin/env bash
#
# Split a Webshare proxy CSV across N worker containers and emit a
# docker-compose override file. Each worker gets its own dedicated slice
# of proxies via the MAPO_PROXY_URLS env var, so two workers never hit
# the same IP at the same time.
#
# Usage:
#   scripts/partition-proxies.sh CSV PROXIES_PER_WORKER [OUTPUT_FILE]
#
# Example:
#   # 100-line Webshare CSV → 10 workers × 10 proxies each
#   scripts/partition-proxies.sh ~/Downloads/webshare.csv 10
#
#   # 100-line CSV → 5 workers × 20 proxies each
#   scripts/partition-proxies.sh ~/Downloads/webshare.csv 20
#
# Then bring up the cluster:
#
#   docker compose --profile distributed \
#       -f docker-compose.yaml -f docker-compose.workers.yaml up -d
#
# To re-partition (e.g. after rotating proxies), just re-run the script —
# it overwrites the output file.

set -euo pipefail

if [ $# -lt 2 ] || [ "${1:-}" = "-h" ] || [ "${1:-}" = "--help" ]; then
  cat <<EOF >&2
usage: $0 PROXY_CSV PROXIES_PER_WORKER [OUTPUT_FILE]

  PROXY_CSV             path to the Webshare CSV download
                        (https://proxy.webshare.io/proxy/list/download/)
  PROXIES_PER_WORKER    how many dedicated proxies to give each worker
                        (rule of thumb: 5–15 datacenter IPs / worker)
  OUTPUT_FILE           defaults to docker-compose.workers.yaml

The output file is a docker-compose override that:
  * disables the default 'worker' service from docker-compose.yaml
  * defines worker-1 .. worker-N, each with its own MAPO_PROXY_URLS

Re-running the script overwrites OUTPUT_FILE in place.
EOF
  exit 2
fi

csv=$1
per_worker=$2
output=${3:-docker-compose.workers.yaml}

if [ ! -r "$csv" ]; then echo "error: cannot read $csv" >&2; exit 1; fi
case "$per_worker" in ''|*[!0-9]*) echo "error: PROXIES_PER_WORKER must be a positive integer" >&2; exit 2 ;; esac
if [ "$per_worker" -lt 1 ]; then echo "error: PROXIES_PER_WORKER must be >= 1" >&2; exit 2; fi

# Parse the CSV into proxy URLs (skip header, drop blank/short rows, strip CR).
mapfile -t proxies < <(
  tail -n +2 "$csv" | awk -F',' '
    NF < 4 { next }
    $1 == "" { next }
    {
      gsub(/\r/, "")
      printf "http://%s:%s@%s:%s\n", $3, $4, $1, $2
    }
  '
)

total=${#proxies[@]}
if [ "$total" -eq 0 ]; then
  echo "error: no valid proxy rows found in $csv (expected: ip,port,user,pass,...)" >&2
  exit 1
fi

# Compute number of workers — ceiling division.
n_workers=$(( (total + per_worker - 1) / per_worker ))
last_chunk_size=$(( total - per_worker * (n_workers - 1) ))

echo "$total proxies → $n_workers workers (last worker gets $last_chunk_size proxies)" >&2

# Emit the override file.
{
  cat <<EOF
# Generated by scripts/partition-proxies.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
#
# $total proxies split across $n_workers workers ($per_worker per worker;
# the last worker may get fewer if total isn't evenly divisible).
#
# Run with:
#   docker compose --profile distributed \\
#       -f docker-compose.yaml -f $(basename "$output") up -d
#
# Re-partition by re-running:
#   scripts/partition-proxies.sh $csv $per_worker

services:

  # Suppress the default scaled 'worker' service from docker-compose.yaml.
  # The workers below replace it; assigning a profile no one activates is
  # the cleanest way to neutralize a service via an override.
  worker:
    profiles: ["disabled-by-partition"]

EOF

  i=0
  while [ "$i" -lt "$n_workers" ]; do
    n=$(( i + 1 ))
    start=$(( i * per_worker ))
    end=$(( start + per_worker ))
    if [ "$end" -gt "$total" ]; then end=$total; fi

    # Build comma-separated slice for this worker.
    slice=""
    j=$start
    while [ "$j" -lt "$end" ]; do
      if [ -z "$slice" ]; then slice="${proxies[$j]}"
      else slice="$slice,${proxies[$j]}"; fi
      j=$(( j + 1 ))
    done

    cat <<EOF
  worker-$n:
    build: .
    profiles: ["distributed"]
    init: true
    shm_size: 800m
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      MAPO_DB_URL: "postgresql://mapo:mapo@postgres:5432/mapo"
      MAPO_PROXY_URLS: "$slice"
    volumes:
      - ./data:/app/data:z
      - ./mapo.yaml:/app/mapo.yaml:ro,z
    env_file:
      - .env
    command: ["python", "run.py", "worker", "--worker-id", "worker-$n"]

EOF
    i=$n
  done
} > "$output"

echo "wrote $output" >&2
